"""added user table for auth

Revision ID: 310d2a14870b
Revises: a51ec498cfff
Create Date: 2025-04-29 00:13:18.636708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310d2a14870b'
down_revision = 'a51ec498cfff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
